### PR TITLE
added python requirements.txt

### PR DESCRIPTION
**Pull request by SCOTTLB**
will make pip installation easier

### CODE REVIEW

**Review by TheHairyJ — COMMENTED** [review]
Thanks for the PR.

Are all of the packages listed needed?

Jamie

**Comment by SCOTTLB** [comment]
Yup, dependencies. Built in a clean enviroment so nothing extra

**Comment by TheHairyJ** [comment]
Could you edit the README to reflect the steps needed?

**Comment by SCOTTLB** [comment]
Fixed, moved api keys to file to avoid commiting them to repo

**Comment by TheHairyJ** [comment]
Thanks for your contributions.

**Pull request merged**
